In [5]:
import pandas as pd

df = pd.read_csv("house_data.csv")
df.info()
pd.set_option('display.max_columns',None)
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21613 non-null  float64
 1   bedrooms       21613 non-null  int64
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64
 4   sqft_lot       21613 non-null  int64
 5   floors         21613 non-null  float64
 6   waterfront     21613 non-null  int64
 7   view           21613 non-null  int64
 8   condition      21613 non-null  int64
 9   grade          21613 non-null  int64
 10  sqft_above     21613 non-null  int64
 11  sqft_basement  21613 non-null  int64
 12  yr_built       21613 non-null  int64
 13  yr_renovated   21613 non-null  int64
 14  zipcode        21613 non-null  int64
 15  lat            21613 non-null  float64
 16  long           21613 non-null  float64
 17  sqft_living15  21613 non-null  int64
 18  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(14)
memory usage: 3.1 MB

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

####  créer des variables indicatrices pour la colonne "zipcode"

In [156]:
df = pd.get_dummies(df, columns=['zipcode'])
df.head ()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15,zipcode_98001,zipcode_98002,zipcode_98003,zipcode_98004,zipcode_98005,zipcode_98006,zipcode_98007,zipcode_98008,zipcode_98010,zipcode_98011,zipcode_98014,zipcode_98019,zipcode_98022,zipcode_98023,zipcode_98024,zipcode_98027,zipcode_98028,zipcode_98029,zipcode_98030,zipcode_98031,zipcode_98032,zipcode_98033,zipcode_98034,zipcode_98038,zipcode_98039,zipcode_98040,zipcode_98042,zipcode_98045,zipcode_98052,zipcode_98053,zipcode_98055,zipcode_98056,zipcode_98058,zipcode_98059,zipcode_98065,zipcode_98070,zipcode_98072,zipcode_98074,zipcode_98075,zipcode_98077,zipcode_98092,zipcode_98102,zipcode_98103,zipcode_98105,zipcode_98106,zipcode_98107,zipcode_98108,zipcode_98109,zipcode_98112,zipcode_98115,zipcode_98116,zipcode_98117,zipcode_98118,zipcode_98119,zipcode_98122,zipcode_98125,zipcode_98126,zipcode_98133,zipcode_98136,zipcode_98144,zipcode_98146,zipcode_98148,zipcode_98155,zipcode_98166,zipcode_98168,zipcode_98177,zipcode_98178,zipcode_98188,zipcode_98198,zipcode_98199
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,47.5112,-122.257,1340,5650,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,47.7210,-122.319,1690,7639,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,47.7379,-122.233,2720,8062,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,47.5208,-122.393,1360,5000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,47.6168,-122.045,1800,7503,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [157]:
from sklearn.linear_model import LinearRegression

y = df['price']
X = df.drop("price", axis=1)
# X = df[["bedrooms","bathrooms","sqft_living","sqft_lot","floors","waterfront","view","condition","grade","sqft_above","sqft_basement","yr_built","yr_renovated","lat", "long","sqft_living15","sqft_lot15", "zipcode_98001","zipcode_98002","zipcode_98001","zipcode_98002","zipcode_98003","zipcode_98004","zipcode_98005","zipcode_98006","zipcode_98007","zipcode_98008","zipcode_98010","zipcode_98011","zipcode_98014","zipcode_98019","zipcode_98022","zipcode_98023","zipcode_98024","zipcode_98027","zipcode_98028","zipcode_98029","zipcode_98030","zipcode_98031","zipcode_98032","zipcode_98033","zipcode_98034","zipcode_98038","zipcode_98039","zipcode_98040","zipcode_98042","zipcode_98045","zipcode_98052","zipcode_98053","zipcode_98055","zipcode_98056","zipcode_98058","zipcode_98059","zipcode_98065","zipcode_98070","zipcode_98072","zipcode_98074","zipcode_98075","zipcode_98077","zipcode_98092","zipcode_98102","zipcode_98103","zipcode_98105","zipcode_98106","zipcode_98107","zipcode_98108","zipcode_98109","zipcode_98112","zipcode_98115","zipcode_98116","zipcode_98117","zipcode_98118","zipcode_98119","zipcode_98122","zipcode_98125","zipcode_98126","zipcode_98133","zipcode_98136","zipcode_98144","zipcode_98146","zipcode_98148","zipcode_98155","zipcode_98166","zipcode_98168","zipcode_98177","zipcode_98178","zipcode_98188","zipcode_98198","zipcode_98199"]]

model= LinearRegression()
model.fit(X,y)
model.score(X,y)

0.8082920359173373

In [213]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

y = df["price"]
X = df.drop("price", axis=1)
# X = df[["bedrooms","bathrooms","sqft_living","sqft_lot","floors","waterfront","view","condition","grade","sqft_above","sqft_basement","yr_built","yr_renovated","lat", "long","sqft_living15","sqft_lot15", "zipcode_98001","zipcode_98002","zipcode_98001","zipcode_98002","zipcode_98003","zipcode_98004","zipcode_98005","zipcode_98006","zipcode_98007","zipcode_98008","zipcode_98010","zipcode_98011","zipcode_98014","zipcode_98019","zipcode_98022","zipcode_98023","zipcode_98024","zipcode_98027","zipcode_98028","zipcode_98029","zipcode_98030","zipcode_98031","zipcode_98032","zipcode_98033","zipcode_98034","zipcode_98038","zipcode_98039","zipcode_98040","zipcode_98042","zipcode_98045","zipcode_98052","zipcode_98053","zipcode_98055","zipcode_98056","zipcode_98058","zipcode_98059","zipcode_98065","zipcode_98070","zipcode_98072","zipcode_98074","zipcode_98075","zipcode_98077","zipcode_98092","zipcode_98102","zipcode_98103","zipcode_98105","zipcode_98106","zipcode_98107","zipcode_98108","zipcode_98109","zipcode_98112","zipcode_98115","zipcode_98116","zipcode_98117","zipcode_98118","zipcode_98119","zipcode_98122","zipcode_98125","zipcode_98126","zipcode_98133","zipcode_98136","zipcode_98144","zipcode_98146","zipcode_98148","zipcode_98155","zipcode_98166","zipcode_98168","zipcode_98177","zipcode_98178","zipcode_98188","zipcode_98198","zipcode_98199"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=49)

model= LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8250244566713034

In [11]:
model.predict(X_test)

array([ 225597.22823947,  517773.76969648, 1901052.95796076, ...,
       1086872.79857809,  365693.56417319,  305440.98543878])

# Evaluer les résultats de la prédiction

In [227]:
import numpy as np

overview_y_pred = model.predict(X_test)
overview_y_test = y_test

overview = pd.DataFrame(data=np.column_stack((overview_y_pred,overview_y_test)),
                        columns=['Predictions','Valeurs Réelles'])

overview.head(10)

    Predictions  Valeurs Réelles
0  2.389475e+05         331000.0
1  4.933410e+05         579000.0
2  2.812029e+06        4000000.0
3  5.335678e+05         625000.0
4  4.564410e+05         375000.0
5  2.003897e+05         465000.0
6  3.661643e+05         400000.0
7  2.385175e+05         259000.0
8  3.593776e+05         397000.0
9  4.673668e+05         420000.0

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

y = df["price"]
X = df.drop("price", axis=1)
# X = df[["bedrooms","bathrooms","sqft_living","sqft_lot","floors","waterfront","view","condition","grade","sqft_above","sqft_basement","yr_built","yr_renovated","lat", "long","sqft_living15","sqft_lot15", "zipcode_98001","zipcode_98002","zipcode_98001","zipcode_98002","zipcode_98003","zipcode_98004","zipcode_98005","zipcode_98006","zipcode_98007","zipcode_98008","zipcode_98010","zipcode_98011","zipcode_98014","zipcode_98019","zipcode_98022","zipcode_98023","zipcode_98024","zipcode_98027","zipcode_98028","zipcode_98029","zipcode_98030","zipcode_98031","zipcode_98032","zipcode_98033","zipcode_98034","zipcode_98038","zipcode_98039","zipcode_98040","zipcode_98042","zipcode_98045","zipcode_98052","zipcode_98053","zipcode_98055","zipcode_98056","zipcode_98058","zipcode_98059","zipcode_98065","zipcode_98070","zipcode_98072","zipcode_98074","zipcode_98075","zipcode_98077","zipcode_98092","zipcode_98102","zipcode_98103","zipcode_98105","zipcode_98106","zipcode_98107","zipcode_98108","zipcode_98109","zipcode_98112","zipcode_98115","zipcode_98116","zipcode_98117","zipcode_98118","zipcode_98119","zipcode_98122","zipcode_98125","zipcode_98126","zipcode_98133","zipcode_98136","zipcode_98144","zipcode_98146","zipcode_98148","zipcode_98155","zipcode_98166","zipcode_98168","zipcode_98177","zipcode_98178","zipcode_98188","zipcode_98198","zipcode_98199"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=49)

model= LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)


cross_val_score(LinearRegression(),X_train, y_train, cv=5, scoring='accuracy').mean()

/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 95, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

  warnings.warn(
/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 95, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

  warnings.warn(
/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 95, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

  warnings.warn(
/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 95, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

  warnings.warn(
/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 221, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/apprenant/miniconda3/envs/machinelearning/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 95, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

  warnings.warn(

nan

KeyError: 0